//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.Deer.Enum
{
    public enum CarMoveType
    {
        /// <summary>
        /// 水平
        /// </summary>
        HORIZONTAL = 1,
        /// <summary>
        /// 垂直
        /// </summary>
        VERTICAL = 2,
    }
}
