//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Deer
{

public sealed partial class CarEntityData :  Bright.Config.BeanBase 
{
    public CarEntityData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AssetPath = _buf.ReadString();
        Name = _buf.ReadString();
        MoveType = _buf.ReadInt();
        StartPos = _buf.ReadUnityVector3();
        VictoryPos = _buf.ReadUnityVector3();
        PostInit();
    }

    public static CarEntityData DeserializeCarEntityData(ByteBuf _buf)
    {
        return new Deer.CarEntityData(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 实体的名称
    /// </summary>
    public string AssetPath { get; private set; }
    /// <summary>
    /// 实体的名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 移动类型
    /// </summary>
    public int MoveType { get; private set; }
    /// <summary>
    /// 初始位置
    /// </summary>
    public UnityEngine.Vector3 StartPos { get; private set; }
    /// <summary>
    /// 胜利位置
    /// </summary>
    public UnityEngine.Vector3 VictoryPos { get; private set; }

    public const int __ID__ = 1689791521;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetPath:" + AssetPath + ","
        + "Name:" + Name + ","
        + "MoveType:" + MoveType + ","
        + "StartPos:" + StartPos + ","
        + "VictoryPos:" + VictoryPos + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
