//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Deer
{

public sealed partial class CarMoveLevelData :  Bright.Config.BeanBase 
{
    public CarMoveLevelData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EntityId = _buf.ReadInt();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);CarEntityId = new System.Collections.Generic.List<int>(n);for(var i = 0 ; i < n ; i++) { int _e;  _e = _buf.ReadInt(); CarEntityId.Add(_e);}}
        PostInit();
    }

    public static CarMoveLevelData DeserializeCarMoveLevelData(ByteBuf _buf)
    {
        return new Deer.CarMoveLevelData(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 实例ID
    /// </summary>
    public int EntityId { get; private set; }
    /// <summary>
    /// 使用的EntityId
    /// </summary>
    public System.Collections.Generic.List<int> CarEntityId { get; private set; }

    public const int __ID__ = -1144358391;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EntityId:" + EntityId + ","
        + "CarEntityId:" + Bright.Common.StringUtil.CollectionToString(CarEntityId) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
